### ISSUE TITLE
[blocking]: Unable to install dnvm (optimistic) when user name has a space

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/dnvm#190]
From aspnet/home I pasted the install script into a cmd window on Windows where my username is "Sayed Hashimi" and ran into the following error.

```
C:\temp\_NET\WebApplication3\src\WebApplication3>@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('ht
tps://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
Using temporary directory: C:\Users\SAYEDH~1\AppData\Local\Temp\dnvminstall
Downloading DNVM.ps1 to
Downloading DNVM.cmd to
Installing DNVM
WARNING: Found a KRE_HOME environment variable. This variable has been deprecated and should be removed, or it may interfere with DNVM and the .NET Execution environment
Installing .NET Version Manager to C:\Users\Sayed Hashimi\.dnx\bin
Installing 'dnvm.ps1' to 'C:\Users\Sayed Hashimi\.dnx\bin' ...
Installing 'dnvm.cmd' to 'C:\Users\Sayed Hashimi\.dnx\bin' ...
Adding C:\Users\Sayed Hashimi\.dnx\bin to Process PATH
Adding C:\Users\Sayed Hashimi\.dnx\bin to User PATH
Adding C:\Users\Sayed Hashimi\.dnx to Process DNX_HOME
Adding C:\Users\Sayed Hashimi\.dnx to User DNX_HOME
'""C:\Users\Sayed' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
```

Working around this is tricky because the scripts download other scripts which need to be modified. This is a really bad experience and I think usernames with a space may be common (don't have any data on that).

**Comment by wangkanai** [comment]
Having the same problem here too #192

**Comment by sayedihashimi** [comment]
@damianedwards @davidfowl this is a blocking issue for users with a space in their username. Can someone take a look? I think it's a regression as week.

**Comment by muratg** [comment]
@glennc looks like more folks are hitting this. Could you take a look when you have time? Otherwise, I'll ask @anurse :)

**Comment by sayedihashimi** [comment]
If we can't get it fixed soon we should at least have a documented workaround.

**Comment by janna173** [comment]
I am getting the same error although this seemed to be fixed?!
Any suggestions what to do?

**Comment by markrullo** [comment]
I'm still stuck with this one if anyone can lend a hand I'd appreciate it.  
* I've moved the .dnx directory to c:\.dnx
* I edited the temp-set-envvars.cmd to point the path to the new location
* I did an upgrade, and it still tries to install to my userdirectory
* My userdirectory is c:\users\firstname lastname\

**Comment by muratg** [comment]
@markrullo Does your dnvm.cmd contain the change in https://github.com/aspnet/dnvm/pull/224/files?

**Comment by markrullo** [comment]
@muratg Thank you so much for the help! In scrolling up, I now see where that solution was.  Sorry I didn't find it on my own.  That seemed to do it for me.  I first fixed up the file in;
C:\Program Files\Microsoft DNX\Dnvm
then I did the file in;
C:\Users\my name\.dnx\bin

It was the second one that seemed to do it for me as far as now being able to use dnvm.

I still can't get my web project to host in IIS on this machine (with the space in the user name), but the same project runs fine on my home machine.  I'm not sure if they're related issues.

**Comment by muratg** [comment]
@markrullo I think you have two versions of the dnvm.cmd on box, one installed with a previous version of VS, and one via instructions on Home repo.  You can actually delete the first one.  We're going to be doing this properly in VS RTM / ASP.NET 5 Beta 5 and you'll only have one copy.

Can you file a bug with repro steps on the Hosting repo for the IIS issue?  Thanks!

**Comment by markrullo** [comment]
@muratg Thank you again for the help, and patience with an DNX Newb.

**Comment by nehaabrol87** [comment]
I am facing a kind of similar issue.My username is neha abrol.
When I run dnx restore from visual studio code I get the error as C:/Users/neha is not recognised as an internal or external command

**Comment by muratg** [comment]
@nehaabrol87 What's the dnvm version you're using?

**Comment by nehaabrol87** [comment]
1.0.0-beta7

**Comment by muratg** [comment]
@nehaabrol87 re-read your comment. Are you doing a `dnu restore` or `dnx restore` (which is wrong.)  And are you trying to restore packages (in which case, you should do a `dnu restore` in the folder where your project is) or are you trying to use `dnvm` for managing your `dnx` installations?

**Comment by ucin** [comment]
I still have this issue.

Here what I do,
1. Running cmd as admin I execute following command
  `@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';$wc=New-Object System.Net.WebClient;$wc.Proxy=[System.Net.WebRequest]::DefaultWebProxy;$wc.Proxy.Credentials=[System.Net.CredentialCache]::DefaultNetworkCredentials;Invoke-Expression ($wc.DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"`
 And the ouput is
 ![image](https://cloud.githubusercontent.com/assets/387567/10943849/e4689ca4-8348-11e5-800e-ffeb530c04ec.png)
2. I delete the `dnvm` folder that came with Visual Studio Community 2015
3. Execute `where dnvm` output is
  `C:\Users\Ucin Shahab\.dnx\bin\dnvm.cmd`
4. Performing update with `dnvm upgrade` and output is
  ![image](https://cloud.githubusercontent.com/assets/387567/10943919/36c4227a-8349-11e5-857e-8800aa72174b.png)
5. Execute `dnvm list` produce this
![image](https://cloud.githubusercontent.com/assets/387567/10943946/59fac0be-8349-11e5-9903-d7e01b3ed6b7.png)

My environment,
Windows 10 Enterprise, x64
Visual Studio Community 2015

**Comment by BrennanConroy** [comment]
What version of dnvm

**Comment by ucin** [comment]
Sorry for the delay. Here is output.
![image](https://cloud.githubusercontent.com/assets/387567/10976209/2a65da44-841d-11e5-964c-5f0522f99f8b.png)

**Comment by BrennanConroy** [comment]
Should be fixed with #493

**Comment by Angeland** [comment]
not fixed stil exist

```
C:\Users\Thomas Lian\Desktop\Hjemme Repo\TechNews\src>dnvm list

Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
  *    1.0.0-rc1-final   clr     x86          win
       1.0.0-rc1-update1 clr     x64          win
       1.0.0-rc1-update1 clr     x86          win             default
       1.0.0-rc1-update1 coreclr x64          win
       1.0.0-rc1-update1 coreclr x86          win



'C:\Users\Thomas' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
C:\Users\Thomas Lian\Desktop\Hjemme Repo\TechNews\src>dnvm upgrade
Determining latest version
'dnx-clr-win-x86.1.0.0-rc1-update1' is already installed in C:\Users\Thomas Lian\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1.
Adding C:\Users\Thomas Lian\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin to process PATH
Adding C:\Users\Thomas Lian\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc1-update1'
'C:\Users\Thomas' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
C:\Users\Thomas Lian\Desktop\Hjemme Repo\TechNews\src>where dnvm
C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd
C:\Users\Thomas Lian\.dnx\bin\dnvm.cmd

C:\Users\Thomas Lian\Desktop\Hjemme Repo\TechNews\src>
```

**Comment by muratg** [comment]
@Angeland Does your dnvm.cmd contain the change in https://github.com/aspnet/dnvm/pull/224/files?

**Comment by dylenbrandon** [comment]
I have tried the suggested updates and still cannot get "dnvm upgrade" to function properly. I got here by simply trying to following a tutorial to learn ASP.NET MVC and I can't even get passed the install because of a space in my name? Step 3 of the "Install ASP.NET 5 with Visual Studio" section from [this tutorial](http://docs.asp.net/en/latest/getting-started/installing-on-windows.html) is what got me here.
Sorry if this sounds like a rant, just an unpleasant and painful experience. Ouch. What should I do differently?

**Comment by muratg** [comment]
This is already fixed, you just need to have the fix. Unfortunately RC1 I believe was released with this bug.  And in the next release, we're retiring DNVM (moving to dotnet CLI)

However, you can use the current DNVM builds to unblock yourself.

Try `dnvm update-self` or if that does't work, you can apply the change I called out above to your copy of dnvm.cmd.

**Comment by Angeland** [comment]
@muratg So what will the new command sets be? i thought everything in RC was fairly "future proof"

**Comment by muratg** [comment]
You can find the new command line interface here: https://dotnet.github.io.  Source code: https://github.com/dotnet/cli.   

Please check out this blog post for some information:  https://blogs.msdn.microsoft.com/webdev/2016/01/19/asp-net-5-is-dead-introducing-asp-net-core-1-0-and-net-core-1-0/

dnu restore -> dotnet restore
dnx run -> dotnet run etc.

There are no current plans for a dnvm replacement, but this may change as well.
